# Generated by Django 4.0.1 on 2022-02-01 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=200)),
                ('Age', models.IntegerField(max_length=10)),
                ('Address', models.TextField()),
                ('Grade', models.CharField(max_length=10)),
                ('Major', models.CharField(max_length=20)),
            ],
        ),
    ]
